### ISSUE TITLE
smoke test fails on 32-bit architectures: "Zip archive too large for address space"

### ISSUE THREAD

**Issue by mr-c** [mrkline/piz-rs#15]
Hello,

While packaging the `piz` crate for Debian, we noticed that the tests fail on our 32-bit architectures: `i386` (really i686), `armhf`, and `armel`.

I packaged `piz` due to it being in the dependency chain for a scientific tool, [sourmash](https://github.com/sourmash-bio/sourmash/), which doesn't need 32-bit builds.

So I'm going to disable building `piz` for 32-bit architectures in Debian. But I thought you might want to know.

https://ci.debian.net/packages/r/rust-piz/testing/i386/52816268/ is the log, and I've attached it to this issue just in case.

[piz-i386-log.gz](https://github.com/user-attachments/files/17456427/piz-i386-log.gz)

**Comment by plugwash** [comment]
My understanding is that piz loads the whole archive into the process's address space at once, so it can't be used for large archives on 32-bit system. 

To put it another way I think thi sis a case of the testsuite testing things that simply aren't feasible on 32-bit, but do not indicate that the crate as a whole is not useful on 32-bit.

**Comment by mr-c** [comment]
If there is a patch to skip the problematic tests on 32-bit architectures I will gladly apply it to the Debian package (or update the Debian package to a new release containing the fix).

**Comment by mrkline** [comment]
Hi, and thanks for packaging this!

https://github.com/mrkline/piz-rs/commit/725e8e8d61fb630cd610f0fd50af640a4fbc3099 should be a quick fix; please reopen this issue if it doesn't suit your needs. Happy holidays!
